#!/usr/bin/python
# -*- coding: utf-8 -*-
ot = [
    (u'Bereshit', u'בראשית'),
    (u'Shemot', u'שמות'),
    (u'Vayikra', u'ויקרא'),
    (u'Bemidbar', u'במדבר'),
    (u'Devarim', u'דברים'),
    (u'Yehoshua', u'יהושע'),
    (u'Shoftim', u'שופטים'),
    (u'ShemuelA', u'שמואל א'),
    (u'ShemuelB', u'שמואל ב'),
    (u'MelachimA', u'מלכים א'),
    (u'MelachimB', u'מלכים ב'),
    (u'Yishayah', u'ישעיהו'),
    (u'Yirmiah', u'ירמיהו'),
    (u'Yechezkel', u'יחזקאל'),
    (u'Hoshea', u'הושע'),
    (u'Yoel', u'יואל'),
    (u'Amos', u'עמוס'),
    (u'Ovadyah', u'עבדיה'),
    (u'Yonah', u'יונה'),
    (u'Micha', u'מיכה'),
    (u'Nachum', u'נחום'),
    (u'Chabakuk', u'חבקוק'),
    (u'Zephanyah', u'צפניה'),
    (u'Chagay', u'חגי'),
    (u'Zecharyah', u'זכריה'),
    (u'Malachi', u'מלאכי'),
    (u'DivreiA', u'דברי הימים א'),
    (u'DivreiB', u'דברי הימים ב'),
    (u'Tehilim', u'תהלים'),
    (u'Iyov', u'איוב'),
    (u'Mishley', u'משלי'),
    (u'Rut', u'רות'),
    (u'Shir', u'שיר השירים'),
    (u'Kohelet', u'קהלת'),
    (u'Eicha', u'איכה'),
    (u'Esther', u'אסתר'),
    (u'Daniel', u'דניאל'),
    (u'Ezra', u'עזרא'),
    (u'Nechemiah', u'נחמיה')
]
nt = [
    (u'Matthew', u'מתי'),
    (u'Mark', u'מרקוס'),
    (u'Luke', u'לוקס'),
    (u'John', u'יוחנן'),
    (u'Acts', u'מעשי השליחים'),
    (u'Romans', u'אל הרומים'),
    (u'1Corinthians', u'קורינתים א׳'),
    (u'2Corinthians', u'קורינתים ב׳'),
    (u'Galatians', u'גלטים'),
    (u'Ephesians', u'אפסים'),
    (u'Philippians', u'פיליפים'),
    (u'Colossians', u'קולוסים'),
    (u'1Thessalonians', u'תסלוניקים א׳'),
    (u'2Thessalonians', u'תסלוניקים ב׳'),
    (u'1Timothy', u'טימותיאוס א׳'),
    (u'2Timothy', u'טימותיאוס ב׳'),
    (u'Titus', u'טיטס'),
    (u'Philemon', u'פילמון'),
    (u'Hebrews', u'עברים'),
    (u'James', u'יעקב'),
    (u'1Peter', u'פטרוס א׳'),
    (u'2Peter', u'פטרוס ב׳'),
    (u'1John', u'יוחנן א׳'),
    (u'2John', u'יוחנן ב׳'),
    (u'3John', u'יוחנן ג׳'),
    (u'Jude', u'יהודה'),
    (u'Revelation', u'התגלות')
]
